### ISSUE TITLE
Multimodal posteriors

### ISSUE THREAD

**Issue by darencard** [lliu1871/begfe#3]
I have been running begfe to assess gene family evolution among 8 species of vertebrates based on 10,683 gene families, with rates between lineages unlinked. Here is my configuration file for running begfe:

```
0
geneFamCounts.txt
begfe_ratesUnlinked_results_run1
-1
10683
8
(mm9:318.5,(galGal6:281.8,((gekJap1:191.9,((salMer1:168,(anoCar2:160.8,croVir1:160.8):7.2):7.0,lerBou1:175):16.9):54.0,sphPun1:245.9):35.9):36.7);
250000000 250 0
```

I ran two separate chains with the above configuration. and discarded the first 20% of MCMC repetitions as burn-in, leaving 800k MCMC reps from each chain. Both chains showed similar MCMC characteristics and converged on essentially identical posteriors. In some cases, ESS values were lower than I would have liked, but they appear largely sufficient. I plotted the species tree with divergence times and node labels on each branch to help with interpreting the following information. Happy to provide more details, if necessary.

I am interested in lambda for each node but am seeing a potential issue with multimodal posteriors for several nodes. I have attached graphs of the post-burn-in MCMC traces and densities for these parameters (chains combined) where this is evident for nodes 1-5 and 8. The distribution is strange and it is also centered on the same lambda estimate across the nodes. Moreover, nodes 14-15 are also centered on very similar lambda estimates to the other "problematic" nodes, though the distributions are much smoother and not multimodal. I would not expect lambdas for all of these nodes to be so similar, which also makes me suspicious of the results. Note that while I did not provide the traces/densities for all the other parameters estimates (contraction/no change/expansion), they appear reasonable and do not suffer from the same issues as what I observe for the estimates of lambdas.

I am hoping for some information about why I may be seeing these patterns and how I should consider proceeding with my analysis. Given I have run 2 chains with what appears to be sufficient MCMC reps that have converged on similar results, I'm at a loss for how (or whether) to interpret these results or how I can overcome these potential issues. Any help or advice is greatly appreciated!

![tree](https://user-images.githubusercontent.com/8263623/118154865-92ff0000-b3e5-11eb-8c30-402d659087f0.png)

![1-5](https://user-images.githubusercontent.com/8263623/118153505-fb4ce200-b3e3-11eb-8089-72a31c0ad426.png)

![6-10](https://user-images.githubusercontent.com/8263623/118153514-fee06900-b3e3-11eb-8ce5-db160ec4176a.png)

![10-15](https://user-images.githubusercontent.com/8263623/118153525-0142c300-b3e4-11eb-9608-0458e617d7ac.png)

**Comment by lliu1871** [comment]
Daren,

I apologize for a late response. I was buried with work.

Could you rerun the analysis one more time, specifying a large integer as seed instead of using “-1”, to see if you get a similar result? If it is consistent with the previous results, I would say that the chain has converged to the posterior distribution. The multimodal density curve is artificial due to the small bandwidth 1.55e-07. If you increase the bandwidth, the curve will become smoother.  Because the estimate of lambda is around 0.003137 with a very small standard deviation, the estimates of lambda for different nodes may look similar but are significantly different from each other. You may construct a 95% credible region for each lambda and see if they are overlapped.


Liang
________________________________________________
Graduate coordinator
Department of Statistics
Institute of Bioinformatics
University of Georgia
Phylogenetics Lab | Phylogenetics Lab (uga.edu)<http://faculty.franklin.uga.edu/lliu>

***@***.***D6F55C.C6D67C70]

On May 13, 2021, at 12:29 PM, Daren Card ***@***.******@***.***>> wrote:

[EXTERNAL SENDER - PROCEED CAUTIOUSLY]



I have been running begfe to assess gene family evolution among 8 species of vertebrates based on 10,683 gene families, with rates between lineages unlinked. Here is my configuration file for running begfe:

0
geneFamCounts.txt
begfe_ratesUnlinked_results_run1
-1
10683
8
(mm9:318.5,(galGal6:281.8,((gekJap1:191.9,((salMer1:168,(anoCar2:160.8,croVir1:160.8):7.2):7.0,lerBou1:175):16.9):54.0,sphPun1:245.9):35.9):36.7);
250000000 250 0


I ran two separate chains with the above configuration. and discarded the first 20% of MCMC repetitions as burn-in, leaving 800k MCMC reps from each chain. Both chains showed similar MCMC characteristics and converged on essentially identical posteriors. In some cases, ESS values were lower than I would have liked, but they appear largely sufficient. I plotted the species tree with divergence times and node labels on each branch to help with interpreting the following information. Happy to provide more details, if necessary.

I am interested in lambda for each node but am seeing a potential issue with multimodal posteriors for several nodes. I have attached graphs of the post-burn-in MCMC traces and densities for these parameters (chains combined) where this is evident for nodes 1-5 and 8. The distribution is strange and it is also centered on the same lambda estimate across the nodes. Moreover, nodes 14-15 are also centered on very similar lambda estimates to the other "problematic" nodes, though the distributions are much smoother and not multimodal. I would not expect lambdas for all of these nodes to be so similar, which also makes me suspicious of the results. Note that while I did not provide the traces/densities for all the other parameters estimates (contraction/no change/expansion), they appear reasonable and do not suffer from the same issues as what I observe for the estimates of lambdas.

I am hoping for some information about why I may be seeing these patterns and how I should consider proceeding with my analysis. Given I have run 2 chains with what appears to be sufficient MCMC reps that have converged on similar results, I'm at a loss for how (or whether) to interpret these results or how I can overcome these potential issues. Any help or advice is greatly appreciated!

[tree]<https://user-images.githubusercontent.com/8263623/118154865-92ff0000-b3e5-11eb-8c30-402d659087f0.png>

[1-5]<https://user-images.githubusercontent.com/8263623/118153505-fb4ce200-b3e3-11eb-8089-72a31c0ad426.png>

[6-10]<https://user-images.githubusercontent.com/8263623/118153514-fee06900-b3e3-11eb-8ce5-db160ec4176a.png>

[10-15]<https://user-images.githubusercontent.com/8263623/118153525-0142c300-b3e4-11eb-9608-0458e617d7ac.png>

**Comment by darencard** [comment]
Hi Liang,

Thank you for getting back to me. It took me some time to get back to this, but I did as you recommended and found that a 3rd run of the analysis produced similar results. I was able to successfully summarize my analysis. I appreciate the help and given my issue is solved, I have closed this ticket.

Kind regards,
Daren
